services:
  - type: web
    name: ai-portfolio-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_production.py
    envVars:
      - key: PORT
        value: 8050
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
    healthCheckPath: /
    autoDeploy: true
